### PR TITLE
Provides posibility to transform POT headers in toPot()

### PR DESCRIPTION
**Pull request by alexanderwallin**
Addresses wish in #40 to remove certain POT headers due to Git merge issues.

### CODE REVIEW

**Comment by KornelSzaltanowicz** [comment]
Soo, how can I use it, cause `toPot(data, { transformHeaders: null })` still produces: something like: 

`#: packages/components/src/components/complex/account/river/AccountForm.js:23`
`msgid "Password changed successfully"`
`msgstr ""`
`msgid ""`
`msgstr ""`
`"Content-Type: text/plain; charset=utf-8\n"`
`"POT-Creation-Date: Sun Dec 02 2018 01:22:23 GMT+0100 (CET)\n"`
`"Content-Transfer-Encoding: 8bit\n"`
`"Plural-Forms: nplurals=2; plural=(n != 1);\n"`

Do I do something wrong?

**Comment by sHooKDT** [comment]
> Soo, how can I use it, cause `toPot(data, { transformHeaders: null })` still produces: something like:
> 
> `#: packages/components/src/components/complex/account/river/AccountForm.js:23`
> `msgid "Password changed successfully"`
> `msgstr ""`
> `msgid ""`
> `msgstr ""`
> `"Content-Type: text/plain; charset=utf-8\n"`
> `"POT-Creation-Date: Sun Dec 02 2018 01:22:23 GMT+0100 (CET)\n"`
> `"Content-Transfer-Encoding: 8bit\n"`
> `"Plural-Forms: nplurals=2; plural=(n != 1);\n"`
> 
> Do I do something wrong?

Yes, you need to pass transform function to transformHeaders. For example, if you want to remove POT-Creation-Date header you should write something like this:
```js
function removeCreationDate(headers) {
delete headers['pot-creation-date'];
return headers;
}
```
Or some other way to remove object property. Probably you can either assign null or '' to it.
And then use this function as `toPot(data, { transformHeaders: removeCreationDate })`

**Comment by KornelSzaltanowicz** [comment]
Still not working... But I'm 99% sure that I use this library incorrectly. 
Firstly I tried to execute command similar to that: 

`react-gettext-parser --config path/to/config.js --output messages.pot 'src/**/*.js'` - but ofc. it did not read very nested directories/files. 

Previously I have globpattern similar to that: 
`./packages/{core,components}/src/{views,components,sagas,routes,constants}/{**,**/**,**/**/**}/*.js"`, but as u can see it is very static. I need something which will recursively read all my directories under some path. ex '/src/**/*.js';

This: `**/*.js` will be the best of the bests but it simply not works.. (I've tried both; windows & osx)

I tried many globs to figure out the way to include all required files to translate (notice that I have many nesting levels) - nothing works - I give up with that... 

Second idea was to create recursive method (using node fs) which will iterate over directories and read correct files and then invoke functions in order: 
1. extractMessagesFromFile
2. toPot(message)
And after that just use node filesystem and method: writeStream and append translated pot text to .pot file.

And this seems to work correctly, finally my all files are translated!. 
There is only one problem with this solution... 
For each translated text I get some trash which looks like that: 

#: packages/components/src/components/complex/account/AccountView.js:36
#: packages/components/src/components/complex/account/AccountView.js:67
msgid "Are you sure?"
msgstr ""msgid ""
msgstr ""
"Content-Type: text/plain; charset=utf-8\n"
"POT-Creation-Date: Sun Dec 02 2018 15:44:28 GMT+0100 (CET)\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: packages/components/src/components/complex/account/AccountView.js:66
msgid "Are you sure you want to cancel your account?"
msgstr ""msgid ""
msgstr ""
"Content-Type: text/plain; charset=utf-8\n"
"POT-Creation-Date: Sun Dec 02 2018 15:44:28 GMT+0100 (CET)\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: packages/components/src/components/complex/account/AccountView.js:82
msgid "Basic settings"
msgstr ""
msgid ""
msgstr ""
"Content-Type: text/plain; charset=utf-8\n"
"POT-Creation-Date: Sun Dec 02 2018 15:44:28 GMT+0100 (CET)\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n 


--------------------
So as you can see for each translations it add some extra info about headers, which is not necessay for me... 

What I want to achieve is format like: 

#: packages/components/src/components/complex/account/AccountView.js:82
msgid "Basic settings"
msgstr ""

Any ideas how to resolve these ^?
Or maybe some advise how to use glopattern correctly for each .js file under some dir as this: `'somedir/**/*.js' ` seems to not working...

**Comment by sHooKDT** [comment]
@KornelSzaltanowicz Hmm, your problem looks strange.
It would be nice, if you create some repo with reproduction of this problem, so we can try to debug it.

Personally, I use exactly this code for extracting translations for one individual module of the app.
```

    const rawMessages = extractMessagesFromGlob(
      [`${moduleRoot}/**/*.{js,jsx}`],
      {
        funcArgumentsMap: FUNC_ARGUMENTS_MAP,
      },
    );
    const messagesWithoutRefs = rawMessages.map(removeMessageFileRefs);
    
   const poContents = toPot(messagesWithoutRefs, {
      transformHeaders: transformPoHeaders,
    });

    await writeFileAsync(tempPOFile, poContents);

    await Promise.all(SUPPORTED_LOCALES.map(async (locale) => {
      const pofile = path.join(moduleLocales, `${locale}.po`);
      await mergePOFile(pofile, tempPOFile);
      await stripUnusedTranslations(pofile);
    }));
```
As you can see I use very simple glob that covers any nesting level (e.g. `src/components/App/index.js` ). So, It works perfectly. If you don't need custom options and post-transformations like me, you can simply use parseGlob.

Maybe it will help you.

**Comment by alexanderwallin** [comment]
@KornelSzaltanowicz Should we open a new issue about your strange headers? Is it strictly related to this PR? Can we see your source code?

**Comment by KornelSzaltanowicz** [comment]
This is probably not strictly related to this PR. (Sorry for offtop). 
I need to check @sHooKDT solution and after that I will response. 
If problem will occur again I will provide some repo with code example.

**Comment by KornelSzaltanowicz** [comment]
Ok, I've done some changes and it's works perfectly. What I did wrong was ofc. glob pattern... 
Thank you for your help, appreciate!

**Comment by sHooKDT** [comment]
> Ok, I've done some changes and it's works perfectly. What I did wrong was ofc. glob pattern...
> Thank you for your help, appreciate!

That's nice!

**Comment by alexanderwallin** [comment]
Glad to hear you got things working, @KornelSzaltanowicz. I'm still curious what's on `AccountView.js:82`, which gave you those strange POT results?

**Pull request merged**
